### ISSUE TITLE
Gostaria de entrar em contato com você

### ISSUE THREAD

**Issue by ldepaiva** [wesleimp/nvim#1]
Olá, Wesley. Tudo bem?
Eu estou tentando entrar em contato com você mas não achei seu e-mail ou LinkedIn. Poderia me passar o seu e-mail por favor? Estou procurando um bom desenvolvedor que seja cristão para me ajudar na minha empresa. Abraço

**Comment by wesleimp** [comment]
@ldepaiva wesleimsr@gmail.com
